// 'use server'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../../styles/globals.css'

import { MainLayout } from '@/components/mainLayout'

import { getSession } from '../(auth)/google/_auth/options'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function MailLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout session={session}></MainLayout>
        {children}
      </body>
    </html>
  )
}
