import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../styles/globals.css'

import { MainLayout } from '@/components/mainLayout'
import { ClientProvider } from '@/components/providers/tanstack-provider'

import { getSession } from './(auth)/google/_auth/options'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <ClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>landing layout</div>
          <MainLayout session={session}></MainLayout>
          {children}
        </body>
      </html>
    </ClientProvider>
  )
}
