import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../styles/globals.css'

import { MainLayout } from '@/components/mainLayout'
import { ClientProvider } from '@/components/providers/tanstack-provider'

import { getGmailSession } from './(auth)/google/_auth/options'
import { getTempSession } from './(auth)/temp/_auth/options'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const googleSession = await getGmailSession()
  const tempSession = await getTempSession()
  return (
    <ClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainLayout googleSession={googleSession} tempSession={tempSession}></MainLayout>
          {children}
        </body>
      </html>
    </ClientProvider>
  )
}
